name: SuperbVotePlus
version: ${project.version}
main: io.minimum.minecraft.superbvoteplus.SuperbVotePlus
description: Paper Test Plugin
api-version: '1.19'
authors: [tuxed, Tig3r98]
dependencies:
  server:
    Votifier:
      load: BEFORE
      required: false
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true
    ForestRedisAPI:
      load: BEFORE
      required: false
      join-classpath: true
