name: SuperbVotePlus
main: io.minimum.minecraft.superbvote.SuperbVotePlus
authors: [tuxed, Tig3r98]
version: ${project.version}
depend: [Votifier]
softdepend: [Vault, PlaceholderAPI]
api-version: "1.13"
commands:
  superbvoteplus:
    description: SuperbVotePlus main command.
    aliases: [svp]
  vote:
    description: SuperbVotePlus vote command.
  votestreak:
    description: SuperbVotePlus vote streak command.
    aliases: [vstreak]
permissions:
  superbvote.notify:
    default: true
  superbvote.votes.others:
    default: op
  superbvote.admin:
    default: op
